# Application port
server:
  port: 80

# 상품 이미지 업로드 경로
filePath: /Users/jwkwon0817/IdeaProjects/cs/src/main/resources/assets/

# Spring Boot Config
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cs?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect

# Print Bind Parameter
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
